export default {
    "Ocean": 1,
    "Romance": 2,
    "Sunset": 3,
    "Party": 4,
    "Fireplace": 5,
    "Cozy": 6,
    "Forest": 7,
    "PastelColors": 8,
    "WakeUp": 9,
    "Bedtime": 10,
    "WarmWhite": 11,
    "Daylight": 12,
    "CoolWhite": 13,
    "NightLight": 14,
    "Focus": 15,
    "Relax": 16,
    "TrueColors": 17,
    "TvTime": 18,
    "PlantGrowth": 19,
    "Spring": 20,
    "Summer": 21,
    "Fall": 22,
    "Deepdive": 23,
    "Jungle": 24,
    "Mojito": 25,
    "Club": 26,
    "Christmas": 27,
    "Halloween": 28,
    "Candlelight": 29,
    "GoldenWhite": 30,
    "Pulse": 31,
    "Steampunk": 32,
};

